services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_LISTENERS=SSL://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=SSL://kafka:9093
      - KAFKA_SECURITY_PROTOCOL=SSL
      - KAFKA_SSL_KEYSTORE_TYPE=PKCS12
      - KAFKA_SSL_KEYSTORE_LOCATION=/certs/kafka.pfx
      - KAFKA_SSL_KEYSTORE_PASSWORD=123QWEasd
      - KAFKA_SSL_TRUSTSTORE_TYPE=PKCS12
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/certs/rootCA.pfx
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=123QWEasd
    volumes:
      - ./security/certs:/certs
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  producer:
    build: ./kafka
    depends_on:
      - kafka
    volumes:
      - ./input:/input
      - ./kafka:/kafka
    networks:
      - kafka-network

  spark-master:
    image: bitnami/spark:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_SSL_ENABLED=true
      - SPARK_SSL_KEYSTORE=/certs/spark.pfx
      - SPARK_SSL_KEYSTORE_PASSWORD=123QWEasd
      - SPARK_SSL_KEYSTORE_TYPE=PKCS12
      - SPARK_SSL_TRUSTSTORE=/certs/rootCA.pfx
      - SPARK_SSL_TRUSTSTORE_PASSWORD=123QWEasd
      - SPARK_SSL_TRUSTSTORE_TYPE=PKCS12
    volumes:
      - ./spark:/spark
      - ./security/certs:/certs
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_SSL_ENABLED=true
      - SPARK_SSL_KEYSTORE=/certs/spark.pfx
      - SPARK_SSL_KEYSTORE_PASSWORD=123QWEasd
      - SPARK_SSL_KEYSTORE_TYPE=PKCS12
      - SPARK_SSL_TRUSTSTORE=/certs/rootCA.pfx
      - SPARK_SSL_TRUSTSTORE_PASSWORD=123QWEasd
      - SPARK_SSL_TRUSTSTORE_TYPE=PKCS12
    volumes:
      - ./spark:/spark
      - ./security/certs:/certs
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-submit:
    build: ./spark
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark:/spark
      - ./output:/output
    depends_on:
      - spark-master
      - kafka
      - namenode
    networks:
      - spark-network
      - kafka-network
      - hdfs-network

  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: hdfs namenode
    ports:
      - 9870:9870
      - 8020:8020
    env_file:
      - ./hdfs/config
    environment:
      - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
      - HADOOP_SSL_ENABLED=true
      - HADOOP_SSL_KEYSTORE=/certs/hdfs.pfx
      - HADOOP_SSL_KEYSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_KEYSTORE_TYPE=PKCS12
      - HADOOP_SSL_TRUSTSTORE=/certs/rootCA.pfx
      - HADOOP_SSL_TRUSTSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_TRUSTSTORE_TYPE=PKCS12
    networks:
      - hdfs-network
    volumes:
      - ./hdfs:/hdfs

  datanode:
    image: apache/hadoop:3
    command: [ "hdfs", "datanode" ]
    hostname: localhost
    ports:
      - 9864:9864
    env_file:
      - ./hdfs/config
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HADOOP_SSL_ENABLED=true
      - HADOOP_SSL_KEYSTORE=/certs/hdfs.pfx
      - HADOOP_SSL_KEYSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_KEYSTORE_TYPE=PKCS12
      - HADOOP_SSL_TRUSTSTORE=/certs/rootCA.pfx
      - HADOOP_SSL_TRUSTSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_TRUSTSTORE_TYPE=PKCS12
    networks:
      - hdfs-network

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./hdfs/config
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HADOOP_SSL_ENABLED=true
      - HADOOP_SSL_KEYSTORE=/certs/hdfs.pfx
      - HADOOP_SSL_KEYSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_KEYSTORE_TYPE=PKCS12
      - HADOOP_SSL_TRUSTSTORE=/certs/rootCA.pfx
      - HADOOP_SSL_TRUSTSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_TRUSTSTORE_TYPE=PKCS12
    networks:
      - hdfs-network

  nodemanager:
    image: apache/hadoop:3
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./hdfs/config
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HADOOP_SSL_ENABLED=true
      - HADOOP_SSL_KEYSTORE=/certs/hdfs.pfx
      - HADOOP_SSL_KEYSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_KEYSTORE_TYPE=PKCS12
      - HADOOP_SSL_TRUSTSTORE=/certs/rootCA.pfx
      - HADOOP_SSL_TRUSTSTORE_PASSWORD=123QWEasd
      - HADOOP_SSL_TRUSTSTORE_TYPE=PKCS12
    networks:
      - hdfs-network

networks:
  kafka-network:
    driver: bridge
  spark-network:
    driver: bridge
  hdfs-network:
    driver: bridge
